apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: kuberesilience-cpu-stress
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - boutique
    labelSelectors:
      app: SERVICE_PLACEHOLDER
  stressors:
    cpu:
      workers: 4
      load: 90
  duration: "60s"
