apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kuberesilience-network-latency
  namespace: chaos-mesh
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - boutique
    labelSelectors:
      app: SERVICE_PLACEHOLDER
  delay:
    latency: "300ms"
    jitter: "50ms"
    correlation: "25"
  duration: "60s"
