apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: kuberesilience-packet-loss
  namespace: chaos-mesh
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - boutique
    labelSelectors:
      app: SERVICE_PLACEHOLDER
  loss:
    loss: "45"
    correlation: "25"
  duration: "60s"
