apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kuberesilience-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - boutique
    labelSelectors:
      app: SERVICE_PLACEHOLDER
  duration: "30s"
